on:
  schedule:
    - cron:  "0 14 * * *"
  workflow_dispatch:

name: download_data

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Execute Script
        run: |
          Rscript "spill-data-download.R"
          
      - name: Commit Data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data
          git commit -m "data from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-
